#!/usr/bin/env bash
# installs and configures HAProxy in my lb01 server

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 126078-web-01 35.168.3.37 check
    server 126078-web-02 100.26.173.189 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
