#!/usr/bin/env bash
# installs and configures HAProxy in my lb01 server

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 126078-web-01 34.229.71.182 check
    server 126078-web-02 54.173.20.71 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
